# Makefile

# Default target when running `make`
.PHONY: cello-plan

# Define Terraform variables file
TFVARS_FILE = cello.tfvars

# Terraform Plan target
cello-plan:
	@echo "Running terraform plan with ${TFVARS_FILE}..."
	terraform plan -var-file=${TFVARS_FILE}
cello-apply:
	@echo "Running terraform plan with ${TFVARS_FILE}..."
	terraform apply -var-file=${TFVARS_FILE} --auto-approve
